// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHN3y2SKN980b3bw0Ufho_7MJS3fyi4lU',
    appId: '1:471396108409:web:f78c7f894c655286a26ca8',
    messagingSenderId: '471396108409',
    projectId: 'eztransferdb',
    authDomain: 'eztransferdb.firebaseapp.com',
    storageBucket: 'eztransferdb.appspot.com',
    measurementId: 'G-Z6BCMLCKJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9wFDLZpy9QCWe5fGLUhBhMfcmu1eqlc',
    appId: '1:471396108409:android:e976134236df1b72a26ca8',
    messagingSenderId: '471396108409',
    projectId: 'eztransferdb',
    storageBucket: 'eztransferdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsqoahu3CVqMmqDof8hIbd838_QaoATg',
    appId: '1:471396108409:ios:70887d20c04dcc91a26ca8',
    messagingSenderId: '471396108409',
    projectId: 'eztransferdb',
    storageBucket: 'eztransferdb.appspot.com',
    iosBundleId: 'com.example.eztransfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsqoahu3CVqMmqDof8hIbd838_QaoATg',
    appId: '1:471396108409:ios:70887d20c04dcc91a26ca8',
    messagingSenderId: '471396108409',
    projectId: 'eztransferdb',
    storageBucket: 'eztransferdb.appspot.com',
    iosBundleId: 'com.example.eztransfer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHN3y2SKN980b3bw0Ufho_7MJS3fyi4lU',
    appId: '1:471396108409:web:d1b20bd88d45a992a26ca8',
    messagingSenderId: '471396108409',
    projectId: 'eztransferdb',
    authDomain: 'eztransferdb.firebaseapp.com',
    storageBucket: 'eztransferdb.appspot.com',
    measurementId: 'G-PRWN3R7DZ5',
  );
}
